--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Cosmoverse/FloatingText
build-by-default: true
branches:
- master
projects:
  FloatingText:
    path: ""
    lint:
      phpstan: false
    libs:
      - src: poggit/libasynql/libasynql
        version: ^3.4.0
        branch: "4.0"
...
