name: FloatingText
main: cosmicpe\floatingtext\Loader
api: 5.0.0
version: 0.1.2
commands:
  floatingtext:
    aliases: [ft]
    permission: floatingtext.command
permissions:
  floatingtext.command:
    default: op
